### ISSUE TITLE
August 2019 Newsletter

### ISSUE THREAD

**Issue by haacked** [dotnet-foundation/newsletter#15]
This is a tracking issue for the August 2019 newsletter. The deadline for submissions to this newsletter is August 29 EOD.

__GIVE US YOUR JUICY NEWS!__ 😄 

To submit, send a PR with edits to https://github.com/dotnet-foundation/newsletter/blob/master/2019/08.md

**Comment by netroby** [comment]
Can it be a mail list? want to receive the mail newsletter

**Comment by jongalloway** [comment]
Done!
