### ISSUE TITLE
September 2019 Newsletter

### ISSUE THREAD

**Issue by haacked** [dotnet-foundation/newsletter#25]
This is a tracking issue for the September 2019 newsletter. The deadline for submissions to this newsletter is September 29 EOD.

__GIVE US YOUR JUICY NEWS!__ 😄 

To submit, send a PR with edits to https://github.com/dotnet-foundation/newsletter/blob/master/2019/09.md

**Comment by loic-sharma** [comment]
Hello, is it appropriate to submit a project that isn’t part of the .NET Foundation but that makes it easier to interact with a .NET Foundation project (NuGet)? Thanks!

**Comment by glennawatson** [comment]
Hey @loic-sharma have a look at https://github.com/dotnet-foundation/newsletter#who-may-submit-news

**Comment by loic-sharma** [comment]
Ah I had read that document but I seemed to have missed that section. Thanks!

**Comment by haacked** [comment]
The [September newsletter is out](https://dotnetfoundation.org/blog/2019/10/01/net-foundation-september-2019-update). Thanks everyone!
