### ISSUE TITLE
October 2019 Newsletter

### ISSUE THREAD

**Issue by haacked** [dotnet-foundation/newsletter#37]
This is a tracking issue for the October 2019 newsletter. The deadline for submissions to this newsletter is October 29 EOD.

__GIVE US YOUR JUICY NEWS!__ 😄

To submit, go to https://github.com/dotnet-foundation/newsletter/blob/master/2019/10.md, click the edit button, and submit a PR. The [README provides more details including a how-to video](https://github.com/dotnet-foundation/newsletter/blob/master/README.md) for submitting project news.

**Comment by GuruCharan94** [comment]
Proposal : Add the community links from the .NET Community stand-up to the newsletter.
