### ISSUE TITLE
News item for ML.NET 1.2 Release

### ISSUE THREAD

**Issue by jongalloway** [dotnet-foundation/newsletter#7]
https://devblogs.microsoft.com/dotnet/announcing-ml-net-1-2-and-model-builder-updates-machine-learning-for-net/

**Comment by jongalloway** [comment]
@CESARDELATORRE can you or someone on the ML.NET project submit a PR to add a short blurb to https://github.com/dotnet-foundation/newsletter/blob/master/2019/07.md for this?

**Comment by CESARDELATORRE** [comment]
Sure! I just created a PR with some content. 
I put it under the ".NET Foundation Project Updates" section.
Feel free to review/update it if needed. 👍

**Comment by jongalloway** [comment]
Closed by #12
