### ISSUE TITLE
Create a Newsletter Deadline Issue For Each Release

### ISSUE THREAD

**Issue by khalidabuhakmeh** [dotnet-foundation/newsletter#8]
It would be nice to have an issue created for each new release of the newsletter. It does two things:

1. Let folks know when to expect the new release of the newsletter
1. Allow editors of the newsletter to link to the issue in their Pull Requests (effectively giving us a digest of changes)

Just a thought, what do you think @jongalloway and @haacked?

**Comment by haacked** [comment]
Yes!

**Comment by haacked** [comment]
Resolved by #9
