### ISSUE TITLE
Should this repository be archived?

### ISSUE THREAD

**Issue by gep13** [dotnet-foundation/newsletter#82]
Based on this change from 8th May 2020:

https://github.com/dotnet-foundation/newsletter/commit/d06062ddffd29787affa6594946ec2bba834f269

Looks like the submission for entries into the newsletter has changed.

Seems like not everyone got this message, myself included, as there were PR's into this repository:

https://github.com/dotnet-foundation/newsletter/pulls

And some project news wasn't included in the last newsletter.

@clairernovotny @benaadams @IrisClasson @jskeet @SaraJo @haacked @BethMassi

**Comment by BethMassi** [comment]
AFAIK, this is still the correct process for newsletter submissions. @jongalloway helps us with the newsletter and can probably send out an update. I know we had a lot of news this time around and maybe this just slipped through the cracks.

**Comment by gep13** [comment]
This is taken from the link I included above:

> Every month we will create an issue for the upcoming newsletter as well as a markdown file to contain the news. News should be submitted as a pull request to [the current newsletter markdown file](https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md).

**Comment by jongalloway** [comment]
Per @clairernovotny the new process is to update the above linked markdown doc, not via pull requests to this repo. I had also missed that memo until very recently. 

@clairernovotny, do you want to archive this repo or do something else to avoid missing pull requests here?

**Comment by clairernovotny** [comment]
I think it css as n be archived.

**Comment by tomasherceg** [comment]
Do I understand correctly that the process is now to PR this file? 
https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md

Right now, the file contains the same text that was sent in the recent newsletters. Shall we wait until the file is prepared for the next month? Also, when do you send the newsletter? It was changed from monthly to bi-monthly and the last one went out in the middle of the month. 
Have I missed some announcement about what's the process now?

**Comment by gep13** [comment]
@tomasherceg all very good questions.

It would be good to get some clarification about what exactly the process is.

**Comment by clairernovotny** [comment]
Sorry, yes, PR's should go to https://github.com/dotnet-foundation/website/blob/master/input/blog/posts/_current-newsletter-draft.md

That wasn't renamed/reset when the newsletter went out; it's fixed now.
